/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blackjack.server.gui;

import blackjack.server.BlackjackServer;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Patrick
 */
public class ServerUI extends javax.swing.JFrame {
    private final BlackjackServer server;

    /**
     * Creates new form ServerUI
     */
    public ServerUI(BlackjackServer BlackjackServer) {
        this.server = BlackjackServer;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ResetBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BJ_Server_UI");
        setBackground(new java.awt.Color(0, 0, 0));
        setFocusable(false);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 165, 260));
        setMinimumSize(new java.awt.Dimension(165, 250));
        setName("ServerUIFrame"); // NOI18N

        ResetBTN.setBackground(new java.awt.Color(0, 0, 0));
        ResetBTN.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        ResetBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjack/server/gui/ServerUIBackground.png"))); // NOI18N
        ResetBTN.setAlignmentY(0.0F);
        ResetBTN.setBorderPainted(false);
        ResetBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ResetBTN.setFocusPainted(false);
        ResetBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ResetBTN.setPreferredSize(new java.awt.Dimension(150, 220));
        ResetBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ResetBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ResetBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResetBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBTNActionPerformed
        try {
            server.restartApplication();
        } catch (IOException ex) {
            Logger.getLogger(ServerUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ResetBTNActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ResetBTN;
    // End of variables declaration//GEN-END:variables
}
